In [1]:
%scala
val myRange = spark.range(1000).toDF("number")

In [2]:
%python
myRange = spark.range(1000).toDF("number")

In [3]:
%scala
val divisBy2 = myRange.where("number % 2 = 0")

In [4]:
%python
divisBy2 = myRange.where("number % 2 = 0")

In [5]:
%sql
SELECT * FROM myRange WHERE number % 2 = 0

In [6]:
%scala
divisBy2.count()

In [7]:
%python
divisBy2.count()

In [8]:
%sh cd ..
cd ..
cd dbfs/FileStore/tables/8su3wraj1497632771405
ls

In [9]:
%scala
val flightData2015 = spark
.read
.json("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")

In [10]:
%python
flightData2015 = spark\
.read\
.json("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
flightData2015

In [11]:
%scala
flightData2015.take(2)

In [12]:
%python
flightData2015.take(2)

In [13]:
%scala
flightData2015.explain()

In [14]:
flightData2015.explain()

In [15]:
%scala
val sortedFlightData2015 = flightData2015.sort("count")
sortedFlightData2015.explain()

In [16]:
sortedFlightData2015 = flightData2015.sort("count")
sortedFlightData2015.explain()

In [17]:
%scala
sortedFlightData2015.take(2)

In [18]:
sortedFlightData2015.take(2)

In [19]:
%sh cd ..
cd ..
cd dbfs/FileStore/tables/baae5ww01497633203998
ls

In [20]:
%scala
val flightData2015 = spark.read
.option("inferSchema", "true")
.option("header", "true")
.csv("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")
flightData2015

In [21]:
flightData2015 = spark.read\
.option("inferSchema", "true")\
.option("header", "true")\
.csv("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")
flightData2015

In [22]:
%scala
val csvSchema = spark.read.format("csv")
.option("inferSchema", "true")
.option("header", "true")
.load("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")
.schema
val jsonSchema = spark
.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
.schema
println(csvSchema)
println(jsonSchema)

In [23]:
csvSchema = spark.read.format("csv")\
.option("inferSchema", "true")\
.option("header", "true")\
.load("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")\
.schema
jsonSchema = spark.read.format("json")\
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")\
.schema
print(csvSchema)
print(jsonSchema)

In [24]:
%scala
val flightData2015 = spark.read
.schema(jsonSchema)
.option("header", "true")
.csv("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")

In [25]:
flightData2015 = spark.read\
.schema(jsonSchema)\
.option("header", "true")\
.csv("/FileStore/tables/baae5ww01497633203998/2015_summary-ebaee.csv")

In [26]:
%scala
flightData2015.createOrReplaceTempView("flight_data_2015")

In [27]:
flightData2015.createOrReplaceTempView("flight_data_2015")

In [28]:
%scala
val sqlWay = spark.sql("""
SELECT DEST_COUNTRY_NAME, count(1)
FROM flight_data_2015
GROUP BY DEST_COUNTRY_NAME
""")
val dataFrameWay = flightData2015
.groupBy('DEST_COUNTRY_NAME)
.count()
sqlWay.explain
dataFrameWay.explain

In [29]:
sqlWay = spark.sql("""
SELECT DEST_COUNTRY_NAME, count(1)
FROM flight_data_2015
GROUP BY DEST_COUNTRY_NAME
""")
dataFrameWay = flightData2015\
.groupBy("DEST_COUNTRY_NAME")\
.count()
sqlWay.explain()
dataFrameWay.explain()

In [30]:
%sql
SELECT max(count) from summary2015

In [31]:
%scala
import org.apache.spark.sql.functions.max
flightData2015.select(max("count")).take(1)

In [32]:
from pyspark.sql.functions import max
flightData2015.select(max("count")).take(1)

In [33]:
%sql
SELECT DEST_COUNTRY_NAME, sum(count) as destination_total
FROM summary2015
GROUP BY DEST_COUNTRY_NAME
ORDER BY sum(count) DESC
LIMIT 5;

In [34]:
%scala
import org.apache.spark.sql.functions.desc
flightData2015
.groupBy("DEST_COUNTRY_NAME")
.sum("count")
.withColumnRenamed("sum(count)", "destination_total")
.sort(desc("destination_total"))
.limit(5)
.collect()

In [35]:
from pyspark.sql.functions import desc
flightData2015\
.groupBy("DEST_COUNTRY_NAME")\
.sum("count")\
.withColumnRenamed("sum(count)", "destination_total")\
.sort(desc("destination_total"))\
.limit(5)\
.collect()

In [36]:
flightData2015
.groupBy("DEST_COUNTRY_NAME")
.sum("count")
.withColumnRenamed("sum(count)", "destination_total")
.sort(desc("destination_total"))
.limit(5)
.explain()

In [37]:
%scala
val df = spark.range(500).toDF("number")
DataFrames and Datasets | 39
df.select(df.col("number") + 10)
// org.apache.spark.sql.DataFrame = [(number + 10): bigint]

In [38]:
df = spark.range(500).toDF("number")
df.select(df["number"] + 10)
# DataFrame[(number + 10): bigint]

In [39]:
%scala
spark.range(500)

In [40]:
spark.range(500)

In [41]:
%scala
spark.range(2).toDF().collect()

In [42]:
spark.range(2).collect()

In [43]:
%scala
import org.apache.spark.sql.types._
val b = ByteType()

In [44]:
from pyspark.sql.types import *
b = byteType()

In [45]:
%scala
val df = spark.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")

In [46]:
df = spark.read.format("json")\
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
df.printSchema()

In [47]:
%scala
spark.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
.schema

In [48]:
spark.read.format("json")\
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")\
.schema

In [49]:
%scala
import org.apache.spark.sql.types.{StructField, StructType, StringType, LongType}
val myManualSchema = new StructType(Array(
new StructField("DEST_COUNTRY_NAME", StringType, true),
new StructField("ORIGIN_COUNTRY_NAME", StringType, true),
new StructField("count", LongType, false) // just to illustrate flipping this flag
))
val df = spark.read.format("json")
.schema(myManualSchema)
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")

In [50]:
from pyspark.sql.types import StructField, StructType, StringType, LongType
myManualSchema = StructType([
StructField("DEST_COUNTRY_NAME", StringType(), True),
StructField("ORIGIN_COUNTRY_NAME", StringType(), True),
StructField("count", LongType(), False)
])
df = spark.read.format("json")\
.schema(myManualSchema)\
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")

In [51]:
%scala
import org.apache.spark.sql.functions.{col, column}
col("someColumnName")
column("someColumnName")

In [52]:
from pyspark.sql.functions import col, column
col("someColumnName")
column("someColumnName")

In [53]:
%scala
$"myColumn"
'myColumn

In [54]:
%scala
import org.apache.spark.sql.functions.expr
expr("(((someCol + 5) * 200) - 6) < otherCol")

In [55]:
from pyspark.sql.functions import expr
expr("(((someCol + 5) * 200) - 6) < otherCol")

In [56]:
%scala
spark.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
.columns

In [57]:
%scala
df.first()

In [58]:
df.first()

In [59]:
%scala
import org.apache.spark.sql.Row
val myRow = Row("Hello", null, 1, false)

In [60]:
from pyspark.sql import Row
myRow = Row("Hello", None, 1, False)

In [61]:
%scala
myRow(0) // type Any
myRow(0).asInstanceOf[String] // String
myRow.getString(0) // String
myRow.getInt(2) // String

In [62]:
myRow[0]
myRow[2]

In [63]:
%scala
val df = spark.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
df.createOrReplaceTempView("dfTable")

In [64]:
df = spark.read.format("json")\
.load("/FileStore/tables/8su3wraj1497632771405/2015_summary-ebaee.json")
df.createOrReplaceTempView("dfTable")

In [65]:
%scala
import org.apache.spark.sql.Row
import org.apache.spark.sql.types.{StructField, StructType,
StringType, LongType}
val myManualSchema = new StructType(Array(
new StructField("some", StringType, true),
new StructField("col", StringType, true),
new StructField("names", LongType, false) // just to illustrate flipping this flag
))
val myRows = Seq(Row("Hello", null, 1L))
val myRDD = spark.sparkContext.parallelize(myRows)
val myDf = spark.createDataFrame(myRDD, myManualSchema)
myDf.show()

In [66]:
%scala
val myDF = Seq(("Hello", 2, 1L)).toDF()
%python
from pyspark.sql import Row
from pyspark.sql.types import StructField, StructType,\
StringType, LongType
myManualSchema = StructType([
StructField("some", StringType(), True),
StructField("col", StringType(), True),
StructField("names", LongType(), False)
])
myRow = Row("Hello", None, 1)
myDf = spark.createDataFrame([myRow], myManualSchema)
myDf.show()

In [67]:
%scala
df.select("DEST_COUNTRY_NAME").show(2)

In [68]:
%python
df.select("DEST_COUNTRY_NAME").show(2)

In [69]:
%sql
SELECT DEST_COUNTRY_NAME
FROM dfTable
LIMIT 2

In [70]:
%scala
df.select(
"DEST_COUNTRY_NAME",
"ORIGIN_COUNTRY_NAME")
.show(2)

In [71]:
%python
df.select(
"DEST_COUNTRY_NAME",
"ORIGIN_COUNTRY_NAME")\
.show(2)

In [72]:
%sql
SELECT
DEST_COUNTRY_NAME,
ORIGIN_COUNTRY_NAME
FROM
dfTable
LIMIT 2

In [73]:
%scala
import org.apache.spark.sql.functions.{expr, col, column}
df.select(
df.col("DEST_COUNTRY_NAME"),
col("DEST_COUNTRY_NAME"),
column("DEST_COUNTRY_NAME"),
'DEST_COUNTRY_NAME,
$"DEST_COUNTRY_NAME",
  expr("DEST_COUNTRY_NAME")
).show(2)

In [74]:
from pyspark.sql.functions import expr, col, column
df.select(
expr("DEST_COUNTRY_NAME"),
col("DEST_COUNTRY_NAME"),
column("DEST_COUNTRY_NAME"))\
.show(2)

In [75]:
%scala
df.select(expr("DEST_COUNTRY_NAME AS destination"))

In [76]:
%python
df.select(expr("DEST_COUNTRY_NAME AS destination"))

In [77]:
%sql
SELECT
DEST_COUNTRY_NAME as destination
FROM
dfTable

In [78]:
%scala
df.select(
expr("DEST_COUNTRY_NAME as destination").alias("DEST_COUNTRY_NAME")
)

In [79]:
df.select(
expr("DEST_COUNTRY_NAME as destination").alias("DEST_COUNTRY_NAME")
)

In [80]:
%scala
df.selectExpr(
"DEST_COUNTRY_NAME as newColumnName",
"DEST_COUNTRY_NAME")
.show(2)

In [81]:
df.selectExpr(
"DEST_COUNTRY_NAME as newColumnName",
"DEST_COUNTRY_NAME"
).show(2)

In [82]:
%scala
df.selectExpr(
"*", // all original columns
"(DEST_COUNTRY_NAME = ORIGIN_COUNTRY_NAME) as withinCountry"
).show(2)

In [83]:
df.selectExpr(
"*", # all original columns
"(DEST_COUNTRY_NAME = ORIGIN_COUNTRY_NAME) as withinCountry")\
.show(2)

In [84]:
%sql
SELECT
*,
(DEST_COUNTRY_NAME = ORIGIN_COUNTRY_NAME) as withinCountry
FROM
dfTable

In [85]:
%scala
df.selectExpr("avg(count)", "count(distinct(DEST_COUNTRY_NAME))").show(2)

In [86]:
df.selectExpr("avg(count)", "count(distinct(DEST_COUNTRY_NAME))").show(2)

In [87]:
%sql
SELECT
avg(count),
count(distinct(DEST_COUNTRY_NAME))
FROM
dfTable

In [88]:
%scala
import org.apache.spark.sql.functions.lit
df.select(
expr("*"),
lit(1).as("something")
).show(2)

In [89]:
from pyspark.sql.functions import lit
df.select(
expr("*"),
lit(1).alias("One")
).show(2)

In [90]:
%sql
SELECT
*,
1 as One
FROM
dfTable
LIMIT 2

In [91]:
%scala
df.withColumn("numberOne", lit(1)).show(2)

In [92]:
df.withColumn("numberOne", lit(1)).show(2)

In [93]:
%sql
SELECT
1 as numberOne
FROM
dfTable
LIMIT 2

In [94]:
%scala
df.withColumn(
"withinCountry",
expr("ORIGIN_COUNTRY_NAME == DEST_COUNTRY_NAME")
).show(2)

In [95]:
df.withColumn(
"withinCountry",
expr("ORIGIN_COUNTRY_NAME == DEST_COUNTRY_NAME"))\
.show(2)

In [96]:
%scala
df.withColumn(
"Destination",
df.col("DEST_COUNTRY_NAME"))
.columns

In [97]:
%scala
df.withColumnRenamed("DEST_COUNTRY_NAME", "dest").columns

In [98]:
df.withColumnRenamed("DEST_COUNTRY_NAME", "dest").columns

In [99]:
%scala
import org.apache.spark.sql.functions.expr
val dfWithLongColName = df
.withColumn(
"This Long Column-Name",
expr("ORIGIN_COUNTRY_NAME"))

In [100]:
dfWithLongColName = df\
.withColumn(
"This Long Column-Name",
expr("ORIGIN_COUNTRY_NAME"))

In [101]:
%scala
dfWithLongColName
.selectExpr(
"`This Long Column-Name`",
"`This Long Column-Name` as `new col`")
.show(2)

In [102]:
dfWithLongColName\
.selectExpr(
"`This Long Column-Name`",
"`This Long Column-Name` as `new col`")\
.show(2)
dfWithLongColName.createOrReplaceTempView("dfTableLong")

In [103]:
%sql
SELECT `This Long Column-Name` FROM dfTableLong

In [104]:
%scala
dfWithLongColName.select(col("This Long Column-Name")).columns

In [105]:
dfWithLongColName.select(expr("`This Long Column-Name`")).columns

In [106]:
df.drop("ORIGIN_COUNTRY_NAME").columns

In [107]:
dfWithLongColName.drop("ORIGIN_COUNTRY_NAME", "DEST_COUNTRY_NAME")

In [108]:
df.printSchema()
df.withColumn("count", col("count").cast("int")).printSchema()

In [109]:
%sql
SELECT
cast(count as int)
FROM
dfTable

In [110]:
%scala
val colCondition = df.filter(col("count") < 2).take(2)
val conditional = df.where("count < 2").take(2)

In [111]:
colCondition = df.filter(col("count") < 2).take(2)
conditional = df.where("count < 2").take(2)

In [112]:
%sql
SELECT
*
FROM dfTable
WHERE
count < 2

In [113]:
%scala
df.where(col("count") < 2)
.where(col("ORIGIN_COUNTRY_NAME") =!= "Croatia")
.show(2)

In [114]:
df.where(col("count") < 2)\
.where(col("ORIGIN_COUNTRY_NAME") != "Croatia")\
.show(2)

In [115]:
%sql
SELECT *
FROM dfTable
WHERE
count < 2 AND
ORIGIN_COUNTRY_NAME != "Croatia"

In [116]:
%scala
df.select("ORIGIN_COUNTRY_NAME", "DEST_COUNTRY_NAME").count()

In [117]:
df.select("ORIGIN_COUNTRY_NAME", "DEST_COUNTRY_NAME").count()

In [118]:
%sql
SELECT
COUNT(DISTINCT ORIGIN_COUNTRY_NAME, DEST_COUNTRY_NAME)
FROM dfTable

In [119]:
%scala
df.select("ORIGIN_COUNTRY_NAME").distinct().count()

In [120]:
df.select("ORIGIN_COUNTRY_NAME").distinct().count()

In [121]:
%sql
SELECT
COUNT(DISTINCT ORIGIN_COUNTRY_NAME)
FROM dfTable

In [122]:
%scala
val seed = 5
val withReplacement = false
val fraction = 0.5
df.sample(withReplacement, fraction, seed).count()

In [123]:
seed = 5
withReplacement = False
fraction = 0.5
df.sample(withReplacement, fraction, seed).count()

In [124]:
%scala
val dataFrames = df.randomSplit(Array(0.25, 0.75), seed)
dataFrames(0).count() > dataFrames(1).count()

In [125]:
dataFrames = df.randomSplit([0.25, 0.75], seed)
dataFrames[0].count() > dataFrames[1].count()

In [126]:
%scala
import org.apache.spark.sql.Row
val schema = df.schema
val newRows = Seq(
Row("New Country", "Other Country", 5L),
  Row("New Country 2", "Other Country 3", 1L)
)
val parallelizedRows = spark.sparkContext.parallelize(newRows)
val newDF = spark.createDataFrame(parallelizedRows, schema)
df.union(newDF)
.where("count = 1")
.where($"ORIGIN_COUNTRY_NAME" =!= "United States")
.show() // get all of them and we'll see our new rows at the end

In [127]:
from pyspark.sql import Row
schema = df.schema
newRows = [
Row("New Country", "Other Country", 5L),
Row("New Country 2", "Other Country 3", 1L)
]
parallelizedRows = spark.sparkContext.parallelize(newRows)
newDF = spark.createDataFrame(parallelizedRows, schema)
%python
df.union(newDF)\
.where("count = 1")\
.where(col("ORIGIN_COUNTRY_NAME") != "United States")\
.show()

In [128]:
%scala
df.sort("count").show(5)
df.orderBy("count", "DEST_COUNTRY_NAME").show(5)
df.orderBy(col("count"), col("DEST_COUNTRY_NAME")).show(5)

In [129]:
df.sort("count").show(5)
df.orderBy("count", "DEST_COUNTRY_NAME").show(5)
df.orderBy(col("count"), col("DEST_COUNTRY_NAME")).show(5)

In [130]:
%scala
import org.apache.spark.sql.functions.{desc, asc}
df.orderBy(expr("count desc")).show(2)
df.orderBy(desc("count"), asc("DEST_COUNTRY_NAME")).show(2)

In [131]:
from pyspark.sql.functions import desc, asc
df.orderBy(expr("count desc")).show(2)
df.orderBy(desc(col("count")), asc(col("DEST_COUNTRY_NAME"))).show(2)

In [132]:
%sql
SELECT *
FROM dfTable
ORDER BY count DESC, DEST_COUNTRY_NAME ASC

In [133]:
%scala
spark.read.format("json")
.load("/FileStore/tables/8su3wraj1497632771405/*summary-ebaee.json")
.sortWithinPartitions("count")

In [134]:
spark.read.format("json")\
.load("/FileStore/tables/8su3wraj1497632771405/*summary-ebaee.json")\
.sortWithinPartitions("count")

In [135]:
%scala
df.limit(5).show()

In [136]:
df.limit(5).show()

In [137]:
%scala
df.orderBy(expr("count desc")).limit(6).show()

In [138]:
df.orderBy(expr("count desc")).limit(6).show()

In [139]:
%sql
SELECT *
FROM dfTable
LIMIT 6

In [140]:
%scala
df.rdd.getNumPartitions

In [141]:
df.rdd.getNumPartitions()

In [142]:
%scala
df.repartition(5)

In [143]:
df.repartition(5)

In [144]:
%scala
df.repartition(col("DEST_COUNTRY_NAME"))

In [145]:
df.repartition(col("DEST_COUNTRY_NAME"))

In [146]:
%scala
df.repartition(5, col("DEST_COUNTRY_NAME"))

In [147]:
df.repartition(5, col("DEST_COUNTRY_NAME"))

In [148]:
%scala
df.repartition(5, col("DEST_COUNTRY_NAME")).coalesce(2)

In [149]:
df.repartition(5, col("DEST_COUNTRY_NAME")).coalesce(2)

In [150]:
%scala
val collectDF = df.limit(10)
collectDF.take(5) // take works with an Integer count
collectDF.show() // this prints it out nicely
collectDF.show(5, false)
collectDF.collect()

In [151]:
collectDF = df.limit(10)
collectDF.take(5) # take works with an Integer count
collectDF.show() # this prints it out nicely
collectDF.show(5, False)
collectDF.collect()